### ISSUE TITLE
File handle leak

### ISSUE THREAD

**Issue by marcus-leake** [isaaceindhoven/isaac-dotcms-advancedsearch#3]
In nl.isaac.dotcms.searcher.util.SearchableAttributesUtil there is a call to IOUtils.toByteArray(file.getInputStream())
In 2.2 of commons-io the stream is not closed. I believe in 2.6 it is.
This leaks file handles.

**Comment by Xander-Steinmann** [comment]
Thanks, we already noticed a leakage in one of our systems but we hadn't found the cause yet. We'll pick this up.

**Comment by Xander-Steinmann** [comment]
Picked up in https://github.com/isaaceindhoven/isaac-dotcms-advancedsearch/tree/feature/issue-3_file-leackage

**Comment by Xander-Steinmann** [comment]
@marcus-leake : Can you check whether the latest master version works for you? I've tested it locally and the number of open files now stays constant when I use the advanced search.
